#!/bin/sh
# One-time step: imports the local, per-installation CA certificate
# generated by spnav-onshape-bridge into the NSS certificate databases used
# by Firefox and Chromium/Chrome on Linux, so both browsers accept the
# bridge's TLS certificate normally instead of needing a manual
# "add security exception" click-through (which spacenav-ws requires, and
# which trains you to ignore certificate warnings).
#
# Imported with real NSS CA trust (C,,), not "peer trust" (P,,) for a bare
# self-signed leaf: verified empirically (headless Firefox) that Firefox's
# certificate verifier does not reliably accept a peer-trusted self-signed
# leaf without a manual per-site exception, while a CA-trusted leaf issued
# by a locally generated CA validates with no user interaction at all, in
# both Firefox and Chromium. See the comment on tls_ensure_certs() in
# src/tls.c for the full story - including an earlier, incorrect attempt to
# fix an unrelated bug by switching away from CA trust to peer trust, which
# is what caused the manual Firefox exception this script now avoids again.
#
# Safe to re-run; importing an already-trusted cert is a no-op.

set -e

# Under the systemd --user service (StateDirectory=), the cert lives under
# XDG_STATE_HOME; run by hand in the foreground, it defaults to
# XDG_DATA_HOME instead (see src/main.c's default_state_dir()). Check both.
CA_CERT=""
for d in "${XDG_STATE_HOME:-$HOME/.local/state}/spnav-onshape-bridge" \
		"${XDG_DATA_HOME:-$HOME/.local/share}/spnav-onshape-bridge"; do
	if [ -f "$d/ca.crt.pem" ]; then
		CA_CERT="$d/ca.crt.pem"
		break
	fi
done
NICK="spnav-onshape-bridge local CA"

if ! command -v certutil >/dev/null 2>&1; then
	echo "certutil not found. Install the NSS tools package for your distro" >&2
	echo "(Arch: nss, Debian/Ubuntu: libnss3-tools, Fedora: nss-tools) and re-run." >&2
	exit 1
fi

if [ -z "$CA_CERT" ]; then
	echo "No CA certificate found yet under XDG_STATE_HOME or XDG_DATA_HOME." >&2
	echo "Start spnav-onshape-bridge once first (it generates it on first run), then re-run this script." >&2
	exit 1
fi

import_into() {
	db="$1"
	label="$2"
	if [ ! -d "$db" ]; then
		echo "  (skipping $label: no NSS database at $db)"
		return
	fi
	certutil -D -n "$NICK" -d "sql:$db" >/dev/null 2>&1 || true
	if certutil -A -n "$NICK" -t "C,," -i "$CA_CERT" -d "sql:$db"; then
		echo "  imported into $label ($db)"
	else
		echo "  FAILED to import into $label ($db)" >&2
	fi
}

echo "Importing $CA_CERT as a trusted CA..."

# Chromium/Chrome on Linux share the NSS database under ~/.pki/nssdb
CHROME_DB="$HOME/.pki/nssdb"
if [ ! -d "$CHROME_DB" ]; then
	mkdir -p "$CHROME_DB"
	certutil -N -d "sql:$CHROME_DB" --empty-password
fi
import_into "$CHROME_DB" "Chromium/Chrome"

# Firefox keeps a separate profile per install; import into all of them
found_ff=0
for ini in "$HOME"/.mozilla/firefox/profiles.ini "$HOME"/.var/app/org.mozilla.firefox/.mozilla/firefox/profiles.ini; do
	[ -f "$ini" ] || continue
	base=$(dirname "$ini")
	# Reads via a heredoc, not a pipe: `awk | while read` would run the loop
	# in a subshell in POSIX sh, losing the found_ff=1 assignment below once
	# the loop ends.
	while IFS= read -r profdir; do
		[ -n "$profdir" ] || continue
		case "$profdir" in
			/*) full="$profdir" ;;
			*)  full="$base/$profdir" ;;
		esac
		if [ -d "$full" ]; then
			found_ff=1
			import_into "$full" "Firefox profile $(basename "$full")"
		fi
	done <<EOF
$(awk -F= '/^Path=/{print $2}' "$ini")
EOF
done
[ "$found_ff" = 0 ] && echo "  (no Firefox profiles found)"

echo ""
echo "Done. Restart Firefox/Chromium for the change to take effect."
